## İstenenler:
1. Veri kümesini indiriniz.
2. Gerekli/gereksiz bağımsız değişkenleri bulunuz.
3. 5 farklı yönteme göre regresyon modellerini çıkartınız.
    - MLR, PR, SVR, DT, RF
4. Yöntemlerin başarılarını karşılaştırınız.
5. 10 yıl tecrübeli ve 100 puan almış bir CEO ve aynı özelliklere sahip bir müdürün maaşlarını tahmin edip sonuçlarını yorumlayınız.

In [58]:
# Gerekli kütüphaneleri içeri aktarıyoruz.
import numpy as np 
import pandas as pd
from sklearn.metrics import r2_score
import statsmodels.api as sm

In [59]:
dataFrame = pd.read_csv("maaslar_yeni.csv")
dataFrame

Calisan ID             unvan  UnvanSeviyesi  Kidem  Puan   maas
0            1             Cayci              1      5    70   2250
1            2          Sekreter              2      5    70   2500
2            3  Uzman Yardimcisi              3      5    70   3000
3            4             Uzman              4      5    70   4000
4            5  Proje Yoneticisi              5      5    70   5500
5            6               Sef              6      5    70   7500
6            7             Mudur              7      5    70  10000
7            8          Direktor              8      5    70  15000
8            9           C-level              9      5    70  25000
9           10               CEO             10      5    70  50000
10          11             Cayci              1      7    99   2000
11          12          Sekreter              2      7     9   2500
12          13  Uzman Yardimcisi              3      7    62   4000
13          14             Uzman              4      4    38   3000
14          15  Proje Yoneticisi              5      1    80   5000
15          16               Sef              6      2    35   5000
16          17             Mudur              7      8    99  12000
17          18          Direktor              8      4    58  11000
18          19           C-level              9      2    20  15000
19          20               CEO             10      4    42  22000
20          21             Cayci              1      8    11   2200
21          22          Sekreter              2      2    53   2200
22          23  Uzman Yardimcisi              3      8    50   2800
23          24             Uzman              4      9    91   6000
24          25  Proje Yoneticisi              5      9    71   5400
25          26               Sef              6      1     2   4000
26          27             Mudur              7     10    81  12000
27          28          Direktor              8     10    38  10000
28          29           C-level              9      1    50  15000
29          30               CEO             10      9    83  60000

## 1. UnvanSeviyesi, Kıdem, Puan değişkenlerini kullanarak maas tahmin etme

In [60]:
X = dataFrame.iloc[:,2:5].values
Y = dataFrame.iloc[:,5:].values

In [61]:
#linear regression
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X,Y)

model=sm.OLS(lin_reg.predict(X),X).fit()
print(model.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.903
Model:                            OLS   Adj. R-squared (uncentered):              0.892
Method:                 Least Squares   F-statistic:                              83.89
Date:                Thu, 17 Aug 2023   Prob (F-statistic):                    8.38e-14
Time:                        16:03:30   Log-Likelihood:                         -295.74
No. Observations:                  30   AIC:                                      597.5
Df Residuals:                      27   BIC:                                      601.7
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [62]:
#polynomial regression
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
x_poly = poly_reg.fit_transform(X)
print(x_poly)
lin_reg2 = LinearRegression()
lin_reg2.fit(x_poly,Y)

model2=sm.OLS(lin_reg2.predict(x_poly),X).fit()
print(model2.summary())

[[1.0000000e+00 1.0000000e+00 5.0000000e+00 ... 1.2250000e+05
  1.7150000e+06 2.4010000e+07]
 [1.0000000e+00 2.0000000e+00 5.0000000e+00 ... 1.2250000e+05
  1.7150000e+06 2.4010000e+07]
 [1.0000000e+00 3.0000000e+00 5.0000000e+00 ... 1.2250000e+05
  1.7150000e+06 2.4010000e+07]
 ...
 [1.0000000e+00 8.0000000e+00 1.0000000e+01 ... 1.4440000e+05
  5.4872000e+05 2.0851360e+06]
 [1.0000000e+00 9.0000000e+00 1.0000000e+00 ... 2.5000000e+03
  1.2500000e+05 6.2500000e+06]
 [1.0000000e+00 1.0000000e+01 9.0000000e+00 ... 5.5800900e+05
  5.1460830e+06 4.7458321e+07]]
                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.680
Model:                            OLS   Adj. R-squared (uncentered):              0.644
Method:                 Least Squares   F-statistic:                              19.11
Date:                Thu, 17 Aug 2023   Prob (F-statistic):                    7.49e

In [63]:
#Verilerin olceklenmesi(scaling)
from sklearn.preprocessing import StandardScaler 

sca1er=StandardScaler()
x_olcekli = sca1er.fit_transform(X)
y_olcekli = sca1er.fit_transform(Y)

#Support Vector Regression
from sklearn.svm import SVR
svr_reg = SVR(kernel='rbf')
svr_reg.fit(x_olcekli,y_olcekli)

model3=sm.OLS(svr_reg.predict(x_olcekli),x_olcekli).fit()
print(model3.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.782
Model:                            OLS   Adj. R-squared (uncentered):              0.758
Method:                 Least Squares   F-statistic:                              32.37
Date:                Thu, 17 Aug 2023   Prob (F-statistic):                    4.34e-09
Time:                        16:03:30   Log-Likelihood:                        -0.92453
No. Observations:                  30   AIC:                                      7.849
Df Residuals:                      27   BIC:                                      12.05
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

/Users/macbook/anaconda3/lib/python3.10/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [64]:
#Decision Tree Regresyon
from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor(random_state=0)
tree_reg.fit(X,Y)

model4=sm.OLS(tree_reg.predict(X),X).fit()
print(model4.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.679
Model:                            OLS   Adj. R-squared (uncentered):              0.644
Method:                 Least Squares   F-statistic:                              19.08
Date:                Thu, 17 Aug 2023   Prob (F-statistic):                    7.62e-07
Time:                        16:03:30   Log-Likelihood:                         -317.95
No. Observations:                  30   AIC:                                      641.9
Df Residuals:                      27   BIC:                                      646.1
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [65]:
#Random Forest Regression
from sklearn.ensemble import RandomForestRegressor
rf_reg=RandomForestRegressor(n_estimators = 10,random_state=0)
rf_reg.fit(X,Y.ravel())

print('Random Forest OLS')
model5=sm.OLS(rf_reg.predict(X),X).fit()
print(model5.summary())

Random Forest OLS
                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.713
Model:                            OLS   Adj. R-squared (uncentered):              0.681
Method:                 Least Squares   F-statistic:                              22.31
Date:                Thu, 17 Aug 2023   Prob (F-statistic):                    1.79e-07
Time:                        16:03:30   Log-Likelihood:                         -316.07
No. Observations:                  30   AIC:                                      638.1
Df Residuals:                      27   BIC:                                      642.3
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------

In [66]:
r2_df1 = pd.DataFrame(data = [r2_score(Y, lin_reg.predict(X)),r2_score(Y, lin_reg2.predict(x_poly)),r2_score(y_olcekli, svr_reg.predict(x_olcekli)),
                             r2_score(Y, tree_reg.predict(X)),r2_score(Y, rf_reg.predict(X))],index = ["Linear","Polynomial","SVR","Decision Tree","Random Forest"],columns=["1.model R2"])

   p-value sonuçlarından da anlaşılabileceği üzere modeli sadece UnvanSeviyesi değişkeni kullanarak yapmak daha doğru olur.

## 2. UnvanSeviyesi değişkenini kullanarak maas tahmin etme


In [67]:
X = dataFrame.iloc[:,2].values.reshape(-1,1) # Bir önceki model aksine sadece tek bir değişkeni alıyorum.
Y = dataFrame.iloc[:,5:].values.reshape(-1,1)

In [68]:
#linear regression
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X,Y)

model=sm.OLS(lin_reg.predict(X),X).fit()
print(model.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.942
Model:                            OLS   Adj. R-squared (uncentered):              0.940
Method:                 Least Squares   F-statistic:                              468.1
Date:                Thu, 17 Aug 2023   Prob (F-statistic):                    1.93e-19
Time:                        16:03:30   Log-Likelihood:                         -287.43
No. Observations:                  30   AIC:                                      576.9
Df Residuals:                      29   BIC:                                      578.3
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [69]:
#polynomial regression
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
x_poly = poly_reg.fit_transform(X)
print(x_poly)
lin_reg2 = LinearRegression()
lin_reg2.fit(x_poly,Y)

model2=sm.OLS(lin_reg2.predict(x_poly),X).fit()
print(model2.summary())

[[1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 2.000e+00 4.000e+00 8.000e+00 1.600e+01]
 [1.000e+00 3.000e+00 9.000e+00 2.700e+01 8.100e+01]
 [1.000e+00 4.000e+00 1.600e+01 6.400e+01 2.560e+02]
 [1.000e+00 5.000e+00 2.500e+01 1.250e+02 6.250e+02]
 [1.000e+00 6.000e+00 3.600e+01 2.160e+02 1.296e+03]
 [1.000e+00 7.000e+00 4.900e+01 3.430e+02 2.401e+03]
 [1.000e+00 8.000e+00 6.400e+01 5.120e+02 4.096e+03]
 [1.000e+00 9.000e+00 8.100e+01 7.290e+02 6.561e+03]
 [1.000e+00 1.000e+01 1.000e+02 1.000e+03 1.000e+04]
 [1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 2.000e+00 4.000e+00 8.000e+00 1.600e+01]
 [1.000e+00 3.000e+00 9.000e+00 2.700e+01 8.100e+01]
 [1.000e+00 4.000e+00 1.600e+01 6.400e+01 2.560e+02]
 [1.000e+00 5.000e+00 2.500e+01 1.250e+02 6.250e+02]
 [1.000e+00 6.000e+00 3.600e+01 2.160e+02 1.296e+03]
 [1.000e+00 7.000e+00 4.900e+01 3.430e+02 2.401e+03]
 [1.000e+00 8.000e+00 6.400e+01 5.120e+02 4.096e+03]
 [1.000e+00 9.000e+00 8.100e+01 7.290e+02 6.56

In [70]:
#Verilerin olceklenmesi(scaling)
from sklearn.preprocessing import StandardScaler 

sca1er=StandardScaler()
x_olcekli = sca1er.fit_transform(X)
y_olcekli = sca1er.fit_transform(Y)

#Support Vector Regression
from sklearn.svm import SVR
svr_reg = SVR(kernel='rbf')
svr_reg.fit(x_olcekli,y_olcekli)

model3=sm.OLS(svr_reg.predict(x_olcekli),x_olcekli).fit()
print(model3.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.770
Model:                            OLS   Adj. R-squared (uncentered):              0.762
Method:                 Least Squares   F-statistic:                              97.19
Date:                Thu, 17 Aug 2023   Prob (F-statistic):                    9.11e-11
Time:                        16:03:30   Log-Likelihood:                         -1.3680
No. Observations:                  30   AIC:                                      4.736
Df Residuals:                      29   BIC:                                      6.137
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

/Users/macbook/anaconda3/lib/python3.10/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [71]:
#Decision Tree Regresyon
from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor(random_state=0)
tree_reg.fit(X,Y)

model4=sm.OLS(tree_reg.predict(X),X).fit()
print(model4.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.751
Model:                            OLS   Adj. R-squared (uncentered):              0.742
Method:                 Least Squares   F-statistic:                              87.29
Date:                Thu, 17 Aug 2023   Prob (F-statistic):                    3.01e-10
Time:                        16:03:30   Log-Likelihood:                         -312.62
No. Observations:                  30   AIC:                                      627.2
Df Residuals:                      29   BIC:                                      628.6
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [72]:
#Random Forest Regression
from sklearn.ensemble import RandomForestRegressor
rf_reg=RandomForestRegressor(n_estimators = 10,random_state=0)
rf_reg.fit(X,Y.ravel())

print('Random Forest OLS')
model5=sm.OLS(rf_reg.predict(X),X).fit()
print(model5.summary())

Random Forest OLS
                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.719
Model:                            OLS   Adj. R-squared (uncentered):              0.709
Method:                 Least Squares   F-statistic:                              74.13
Date:                Thu, 17 Aug 2023   Prob (F-statistic):                    1.75e-09
Time:                        16:03:30   Log-Likelihood:                         -315.35
No. Observations:                  30   AIC:                                      632.7
Df Residuals:                      29   BIC:                                      634.1
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------

In [73]:
r2_df2 = pd.DataFrame(data = [r2_score(Y, lin_reg.predict(X)),r2_score(Y, lin_reg2.predict(x_poly)),r2_score(y_olcekli, svr_reg.predict(x_olcekli)),
                             r2_score(Y, tree_reg.predict(X)),r2_score(Y, rf_reg.predict(X))],index = ["Linear","Polynomial","SVR","Decision Tree","Random Forest"],columns=["2.model R2"])

In [74]:
compare_df = pd.concat([r2_df1,r2_df2],axis=1)
compare_df

1.model R2  2.model R2
Linear           0.585721    0.528581
Polynomial       0.999000    0.817487
SVR              0.628720    0.584187
Decision Tree    1.000000    0.834319
Random Forest    0.947550    0.828408

OLS sonuçlarındaki R2 değerleri ve r2_score() metodu kullanılarak çıkan R2 değerlerinin farklı olmasının sebebi R2'nin ikisinde farklı şekilde hesaplanmasıdır. Ama bu bizim yorum yapmamızı engellemez.

Bu veriler için tek değişkenli modelin daha doğru bir model olduğunu gördük. Fakat uzun uğraşlar yerine Korelasyon kullanarak bunu daha kısa bir şekilde görebiliriz.

In [75]:
print(dataFrame.corr().iloc[:,-1].sort_values())

Kidem            0.117964
Puan             0.201474
Calisan ID       0.226287
UnvanSeviyesi    0.727036
maas             1.000000
Name: maas, dtype: float64


/var/folders/l4/pchdf7b10cs1t5kx4kd2j97h0000gn/T/ipykernel_47834/3311166365.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(dataFrame.corr().iloc[:,-1].sort_values())


maas tahmin ederken onunla en ilişkili değişkene,değişkenlere yukarıdaki şekilde de en başta bakabilir ve modelimizi ona göre oluşturabilirdik.

EN BAŞARILI YÖNTEM TEK DEĞİŞKENLİ(2.MODEL) LINEAR REGRESSION'DUR.

In [76]:
print("CEO tahmin :",lin_reg.predict([[10]]))
print("Müdür tahmin : ",lin_reg.predict([[7]]))

CEO tahmin : [[25944.84848485]]
Müdür tahmin :  [[15889.39393939]]


Eldeki veriseti çok kaliteli olmadığı için böyle bir sonuç çıktı. Ama yöntemlerimiz doğru.